# -*- coding: utf-8 -*-
"""feature engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPJeDvbsQrBIuV2K_Jig8ADb0U-r1nmQ
"""

import pandas as pd
import numpy as np

# --- Load CSV ---
file_path = "/content/sample_data/california_housing_train.csv"  # Change to your file path
df = pd.read_csv(file_path)

print("Original shape:", df.shape)
print("Columns:", df.columns.tolist())

# ─────────────────────────────────────────
# STEP 1: Auto-detect datetime columns
# ─────────────────────────────────────────
datetime_cols = []

for col in df.columns:
    try:
        converted = pd.to_datetime(df[col], infer_datetime_format=True)
        df[col] = converted
        datetime_cols.append(col)
        print(f"  ✔ Detected datetime column: {col}")
    except Exception:
        pass

if not datetime_cols:
    print("⚠ No datetime columns detected. Please convert manually:")
    print('  df["your_col"] = pd.to_datetime(df["your_col"])')

# ─────────────────────────────────────────
# STEP 2: Extract Date/Time Features
# ─────────────────────────────────────────
for col in datetime_cols:
    prefix = col  # feature names will be col_year, col_month, etc.

    df[f"{prefix}_year"]        = df[col].dt.year
    df[f"{prefix}_month"]       = df[col].dt.month
    df[f"{prefix}_day"]         = df[col].dt.day
    df[f"{prefix}_dayofweek"]   = df[col].dt.dayofweek      # 0=Monday, 6=Sunday
    df[f"{prefix}_dayofyear"]   = df[col].dt.dayofyear
    df[f"{prefix}_weekofyear"]  = df[col].dt.isocalendar().week.astype(int)
    df[f"{prefix}_quarter"]     = df[col].dt.quarter
    df[f"{prefix}_is_weekend"]  = df[col].dt.dayofweek.isin([5, 6]).astype(int)
    df[f"{prefix}_is_monthend"]  = df[col].dt.is_month_end.astype(int)
    df[f"{prefix}_is_monthstart"]= df[col].dt.is_month_start.astype(int)

    # Hour/Minute (only if time component exists)
    if df[col].dt.hour.sum() > 0:
        df[f"{prefix}_hour"]    = df[col].dt.hour
        df[f"{prefix}_minute"]  = df[col].dt.minute
        df[f"{prefix}_is_business_hour"] = df[col].dt.hour.between(9, 17).astype(int)

    print(f"\n  Features extracted from '{col}':")
    new_cols = [c for c in df.columns if c.startswith(prefix + "_")]
    for c in new_cols:
        print(f"    + {c}")

# ─────────────────────────────────────────
# STEP 3: (Optional) Drop original datetime cols
# ─────────────────────────────────────────
# Uncomment below if you no longer need raw datetime columns
# df.drop(columns=datetime_cols, inplace=True)

# ─────────────────────────────────────────
# STEP 4: Save Engineered File
# ─────────────────────────────────────────
output_path = "featured_output.csv"
df.to_csv(output_path, index=False)
print(f"\n✅ Feature engineered file saved to: {output_path}")
print("Final shape:", df.shape)